### PR TITLE
Fork updates

### PR DESCRIPTION
**Pull request by voku**
- support for more unicode chars
- language-specific stop-words (disabled by default)
- currency support
- php7 types

---
This change is [Reviewable](https://reviewable.io/reviews/jbroadway/urlify/63)

### CODE REVIEW

**Comment by lux** [comment]
I just had a chance to benchmark how these changes would affect the library's performance. Calling `::filter()` 100k times had the following results:

| Version | Time |
| --- | --- |
| master before voku/portable-ascii merge | 0.936257 |
| master after voku/portable-ascii merge | 5.796683 |
| this branch | 7.003144 |

I don't see this being a performance-critical piece of most apps, since once generated presumably the slugs would be stored somewhere, but I wanted to ask whether there were any options that can be tuned to speed things back up a bit, or if voku/portable-ascii provides any way to fall back to PHP extensions for parts of it when available?

**Comment by voku** [comment]
@lux I optimized the performance of the fork, if you have time, please check it. :)

-> https://github.com/voku/urlify

**Comment by lux** [comment]
Much faster! 1.768 from 5.7 or 7, nice :)

I see you closed the PR though. I didn't mean to imply I wasn't interested in merging your changes, just something I thought to look at to be thorough. Any chance of getting the performance improvements you made into this PR still? That would be awesome.

**Comment by voku** [comment]
@lux I back ported the changes, now we will easily call ```\voku\helper\ASCII::to_ascii()``` :)

**Comment by lux** [comment]
Thanks, much appreciated!

**Pull request merged**
